# Настройка окружения и знакомство с Jupyter Notebook

---
## 1. Виртуальные окружения (venv)

### Что такое виртуальное окружение?

Виртуальное окружение — это изолированная среда для Python-проекта, которая позволяет:
- Устанавливать библиотеки только для конкретного проекта
- Избегать конфликтов версий между разными проектами
- Легко делиться списком зависимостей с другими разработчиками

### Как создать виртуальное окружение?

**Windows:**
```bash
python -m venv my_venv
my_venv\Scripts\activate
```

**macOS/Linux:**
```bash
python3 -m venv my_venv
source my_venv/bin/activate
```

После активации вы увидите `(my_venv)` в начале строки терминала.

---
## 2. Менеджер пакетов pip

### Что такое pip?

`pip` — это менеджер пакетов для Python. С его помощью можно:
- Устанавливать библиотеки из PyPI (Python Package Index)
- Обновлять существующие библиотеки
- Удалять ненужные библиотеки
- Создавать список зависимостей проекта

### Основные команды pip:

```bash
# Установка библиотеки
pip install pandas

# Установка конкретной версии
pip install pandas==2.0.0

# Установка из файла requirements.txt
pip install -r requirements.txt

# Показать установленные библиотеки
pip list

# Информация о конкретной библиотеке
pip show pandas

# Обновление библиотеки
pip install --upgrade pandas
```

### Файл requirements.txt

Это текстовый файл со списком всех библиотек проекта:
```
pandas>=2.0.0
numpy>=1.24.0
matplotlib>=3.7.0
```

---
## 3. Jupyter Notebook

### Что такое Jupyter Notebook?

Jupyter Notebook — это интерактивная среда для:
- Написания и выполнения кода
- Добавления текстовых пояснений
- Визуализации данных
- Документирования процесса анализа

### Типы ячеек:

1. **Code** — для Python кода (выполняется при нажатии Shift+Enter)
2. **Markdown** — для текста, заголовков, списков (как эта ячейка)

### Полезные горячие клавиши:

- `Shift + Enter` — выполнить ячейку и перейти к следующей
- `Ctrl + Enter` — выполнить ячейку и остаться в ней
- `A` — создать ячейку выше (Above)
- `B` — создать ячейку ниже (Below)
- `D + D` — удалить ячейку
- `M` — превратить ячейку в Markdown
- `Y` — превратить ячейку в Code

### Магические команды:

В Jupyter есть специальные команды, начинающиеся с `%`:
- `%pwd` — показать текущую директорию
- `%ls` — показать файлы в директории
- `%time` — измерить время выполнения команды
- `%matplotlib inline` — отображать графики прямо в notebook

---
## 4. Демонстрация: Первые шаги в Jupyter

### Пример: Простой Python код

### Markdown форматирование

Jupyter поддерживает Markdown и в нём можно:
- Создать заголовки разных уровней (# ## ###)
- Создать списки (маркированные и нумерованные)
- Выделить текст **жирным** и *курсивом*
- Вставить код: `print("Hello")`

---
## 5. Практические задачи

### Задача 1: Проверка установки библиотек

**Задание**: Импортируйте библиотеки `numpy`, `pandas`, `matplotlib` и выведите их версии.

**Подсказка**: Используйте `import` и атрибут `__version__`

In [2]:
import numpy
numpy.__version__

'2.0.2'

### Задача 2: Работа с Markdown

**Задание**: Создайте ячейку Markdown ниже, которая содержит:
1. Заголовок "Анализ данных"
2. Список из трех библиотек, которые мы будем изучать:
   - NumPy
   - Pandas
   - Matplotlib
3. Одно предложение о том, что вы хотите делать с данными

*Создайте новую ячейку ниже и измените её тип на Markdown*

### Задача 3: Простые вычисления

**Задание**: Создайте список с температурами за неделю (любые числа) и вычислите:
- Среднюю температуру
- Максимальную температуру
- Минимальную температуру

**Подсказка**: Используйте функции `sum()`, `len()`, `max()`, `min()`

In [ ]:
# Ваш код здесь

### Задача 4: Магические команды

**Задание**:
1. Используйте магическую команду `%pwd` чтобы узнать текущую директорию
2. Используйте `%ls` чтобы увидеть файлы в директории
3. Создайте цикл, который считает сумму чисел от 1 до 1000000, и измерьте время его выполнения с помощью `%time`

In [ ]:
# Ваш код здесь

# Основы NumPy и введение в Pandas

### Импорт библиотек

In [ ]:
# Импортируем необходимые библиотеки
import numpy as np
import pandas as pd

---
## 1. Введение в NumPy

### Что такое NumPy?

**NumPy** (Numerical Python) — это библиотека для работы с многомерными массивами и математических вычислений.

### Зачем нужен NumPy?

- **Скорость**: операции с NumPy в десятки раз быстрее, чем с обычными списками Python
- **Удобство**: простой синтаксис для сложных математических операций
- **Функциональность**: огромное количество встроенных функций

### NumPy vs Python списки:

```python
# Python список
python_list = [1, 2, 3, 4, 5]
doubled = [x * 2 for x in python_list]  # Нужен цикл

# NumPy array
numpy_array = np.array([1, 2, 3, 4, 5])
doubled = numpy_array * 2  # Операция сразу для всех элементов
```

---
## 2. Создание NumPy Arrays


### Способы создания массивов:

### Пример 1: Создание array из списка

In [ ]:
# Создайте numpy array из списка температур

### Пример 2: Создание специальных массивов

In [ ]:
# Создайте массивы с помощью:
# np.zeros() - массив из нулей
# np.ones() - массив из единиц
# np.arange() - последовательность чисел
# np.linspace() - равномерно распределенные числа

### Пример 3: Случайные числа

In [ ]:
# Создайте массив случайных чисел с помощью np.random

---
## 3. Операции с NumPy Arrays

### Математические операции

В NumPy все операции выполняются **поэлементно** (element-wise):

### Пример 4: Арифметические операции

In [ ]:
# Продемонстрируйте сложение, вычитание, умножение, деление массивов
# Например: конвертация температуры из шкалы Фаренгейта в шкалу Цельсия (C = (F - 32) × 5/9)

### Пример 5: Агрегатные функции

In [ ]:
# Используйте функции:
# .sum(), .mean(), .std(), .min(), .max(), .argmin(), .argmax()

---
## 4. Введение в Pandas

### Что такое Pandas?

**Pandas** — это библиотека для анализа и обработки структурированных данных (таблиц).

### Две основные структуры данных:

1. **Series** — одномерный массив с индексами (похож на столбец таблицы)
2. **DataFrame** — двумерная таблица данных (как Excel таблица)

### Почему Pandas?

- Работа с табличными данными
- Легкая фильтрация и группировка
- Чтение/запись различных форматов (CSV, Excel, SQL)
- Инструменты для очистки данных
- Встроенная визуализация

---
## 5. Pandas Series

**Series** — это одномерный массив с метками (индексами).

### Пример 6: Создание Series

In [ ]:
# Создайте Series с температурами и индексами (днями недели)

### Пример 7: Доступ к элементам Series

In [ ]:
# Покажите различные способы доступа к элементам
# По индексу, по метке, срезы

---
## 6. Pandas DataFrame

**DataFrame** — это двумерная таблица с метками строк и столбцов.

### Пример 8: Создание DataFrame из словаря

In [ ]:
# Создайте DataFrame с данными о погоде:
# Колонки: Дата, Температура, Влажность, Осадки

### Пример 9: Создание DataFrame из CSV (вручную создадим данные)

In [ ]:
# Создайте тестовый датасет о погоде за месяц
# Используйте pd.date_range() для дат
# Используйте np.random для случайных значений

---
## 7. Первичный анализ данных

### Основные методы для изучения данных:

### Пример 10: Методы .head() и .tail()

In [ ]:
# Выведите первые 5 и последние 5 строк DataFrame

### Пример 11: Метод .info()

Показывает информацию о структуре DataFrame:
- Количество строк и столбцов
- Типы данных
- Количество непустых значений
- Использование памяти

In [ ]:
# Вызовите метод .info()

### Пример 12: Метод .describe()

Показывает статистику по числовым колонкам:
- count (количество)
- mean (среднее)
- std (стандартное отклонение)
- min, 25%, 50%, 75%, max (квартили)

In [ ]:
# Вызовите метод .describe()

### Пример 13: Атрибуты DataFrame

In [ ]:
# Выведите:
# .shape - размерность (строки, столбцы)
# .columns - названия столбцов
# .index - индекс
# .dtypes - типы данных столбцов

### Пример 14: Доступ к столбцам

In [ ]:
# Покажите разные способы доступа к столбцам:
# df['column_name']
# df.column_name
# df[['col1', 'col2']] - несколько столбцов

---
## 8. Практические задачи

Теперь ваша очередь! Примените полученные знания.

### Задача 1: Работа с NumPy

**Задание**:
1. Создайте numpy array с температурами за 10 дней: [22, 24, 19, 25, 23, 26, 21, 20, 24, 25]
2. Найдите среднюю температуру
3. Найдите, в какой день была максимальная температура
4. Конвертируйте все температуры из Celsius в Fahrenheit (формула: F = C * 9/5 + 32)

**Подсказка**: используйте np.array(), .mean(), .argmax()

In [ ]:
# Ваш код здесь

### Задача 2: Создание Series

**Задание**: Создайте Pandas Series с количеством осадков за неделю (в мм):
- Понедельник: 0
- Вторник: 5
- Среда: 12
- Четверг: 0
- Пятница: 3
- Суббота: 8
- Воскресенье: 0

Выведите дни, когда были осадки (больше 0).

**Подсказка**: используйте булеву индексацию series[series > 0]

In [ ]:
# Ваш код здесь

### Задача 3: Создание DataFrame о погоде

**Задание**: Создайте DataFrame с данными о погоде за неделю:
- Колонки: День, Температура (°C), Влажность (%), Ветер (км/ч), Осадки (мм)
- 7 строк (Пн-Вс)
- Заполните любыми реалистичными значениями

Выведите созданный DataFrame.

In [ ]:
# Ваш код здесь

### Задача 4: Анализ данных

**Задание**: Используя DataFrame из предыдущей задачи:
1. Выведите информацию о DataFrame (.info())
2. Выведите статистику (.describe())
3. Найдите день с максимальной температурой
4. Найдите среднюю влажность за неделю
5. Посчитайте общее количество осадков

**Подсказка**: используйте .idxmax(), .mean(), .sum()

In [ ]:
# Ваш код здесь

### Задача 5: Работа с колонками

**Задание**: Используя ваш DataFrame о погоде:
1. Выберите только колонки "Температура" и "Влажность"
2. Создайте новую колонку "Комфорт", которая равна True, если температура от 20 до 25 градусов И влажность меньше 70%
3. Выведите обновленный DataFrame

**Подсказка**: используйте логические операторы & для "И"

In [ ]:
# Ваш код здесь

### Задача 6: Сохранение и загрузка данных

**Задание**:
1. Сохраните ваш DataFrame о погоде в CSV файл "weather_week.csv" в папке data/
2. Загрузите этот файл обратно в новую переменную
3. Сравните, что исходный и загруженный DataFrame одинаковые (.equals())

**Подсказка**: используйте .to_csv() и pd.read_csv()

In [ ]:
# Ваш код здесь

### Задача 7: Генерация большого датасета

**Задание**: Создайте DataFrame с данными о погоде за целый год (365 дней):
- Дата: используйте pd.date_range('2024-01-01', periods=365)
- Температура: случайные числа от -5 до 35 (np.random.randint)
- Влажность: случайные числа от 30 до 95
- Описание: случайный выбор из ['Ясно', 'Облачно', 'Дождь', 'Снег'] (np.random.choice)

Найдите самый жаркий и самый холодный день года.

In [ ]:
# Ваш код здесь

### Задача 8: Сравнение производительности

**Задание**: Сравните скорость работы Python списка и NumPy array:
1. Создайте Python список из 1 миллиона чисел
2. Создайте NumPy array из 1 миллиона чисел
3. Измерьте время умножения всех элементов на 2 для списка (используя list comprehension)
4. Измерьте время умножения всех элементов на 2 для array
5. Сравните результаты

**Подсказка**: используйте %time или import time

In [ ]:
# Ваш код здесь

### Задача 9: Многомерные массивы

**Задание**: Создайте 2D NumPy array (матрицу) 5x7 с температурами по часам за неделю:
- 5 строк = 5 временных интервалов в день (утро, день, вечер, ночь, полночь)
- 7 столбцов = 7 дней недели
- Значения: случайные температуры

Найдите:
1. Среднюю температуру для каждого дня (по столбцам)
2. Среднюю температуру для каждого времени суток (по строкам)
3. Общую среднюю температуру

**Подсказка**: используйте параметр axis в функциях (.mean(axis=0) или .mean(axis=1))

In [ ]:
# Ваш код здесь

# Фильтрация и выборка данных в Pandas

---
## 1. Выборка колонок

### Способы выбора колонок:

1. **Одна колонка**: `df['column_name']` или `df.column_name` → возвращает Series
2. **Несколько колонок**: `df[['col1', 'col2']]` → возвращает DataFrame
3. **Все колонки кроме некоторых**: `df.drop(['col1'], axis=1)`

### Пример 1: Выбор одной колонки

In [ ]:
# Выберите колонку с температурой
df.drop(['temp'],axis=1)

          date  hum
0   2024-12-02   96
1   2024-12-03   57
2   2024-12-04   89
3   2024-12-05   99
4   2024-12-06   50
..         ...  ...
361 2025-11-28   97
362 2025-11-29   92
363 2025-11-30   58
364 2025-12-01   71
365 2025-12-02   89

[366 rows x 2 columns]

### Пример 2: Выбор нескольких колонок

In [ ]:
# Выберите только дату, температуру и осадки

---
## 2. Индексация: loc vs iloc

### loc - доступ по МЕТКАМ (labels)
- Использует названия строк и столбцов
- Синтаксис: `df.loc[rows, columns]`
- Включает конечное значение в срез

### iloc - доступ по ПОЗИЦИЯМ (integer positions)
- Использует числовые индексы (0, 1, 2, ...)
- Синтаксис: `df.iloc[rows, columns]`
- НЕ включает конечное значение (как обычный Python срез)

### Когда что использовать?
- **loc**: когда знаете название/метку ("дайте строку с датой 2024-01-15")
- **iloc**: когда знаете позицию ("дайте 5-ую строку")

### Пример 3: Использование loc

In [ ]:
# Выберите конкретную строку по индексу
# Выберите диапазон строк
# Выберите строки и колонки одновременно
df2 = df.loc[100:200]
df2

          date  temp  hum
100 2025-03-12    -4   64
101 2025-03-13    -7   72
102 2025-03-14     1   88
103 2025-03-15   -10   90
104 2025-03-16    -7   56
..         ...   ...  ...
196 2025-06-16    -5   51
197 2025-06-17    -5   53
198 2025-06-18    -2   59
199 2025-06-19     2   61
200 2025-06-20     1   70

[101 rows x 3 columns]

### Пример 4: Использование iloc

In [ ]:
# Выберите первую строку
# Выберите первые 5 строк
# Выберите конкретные строки и столбцы по позициям
df2.iloc[0]

date    2025-03-12 00:00:00
temp                     -4
hum                      64
Name: 100, dtype: object

---
## 3. Булева индексация (Boolean Indexing)

**Булева индексация** — это фильтрация данных по условию.

### Как это работает:
1. Создаем условие (например, `df['Temperature'] > 25`)
2. Получаем Series из True/False
3. Используем эту Series для фильтрации: `df[condition]`

### Операторы сравнения:
- `==` равно
- `!=` не равно
- `>` больше
- `<` меньше
- `>=` больше или равно
- `<=` меньше или равно

### Пример 5: Простая фильтрация

In [ ]:
# Найдите все дни, когда температура была выше 25°C
df.loc[df['temp'] > 0]

          date  temp  hum
5   2024-12-07     4   77
6   2024-12-08     1   96
8   2024-12-10     3   83
12  2024-12-14     4   60
18  2024-12-20     3   50
..         ...   ...  ...
347 2025-11-14     2   68
348 2025-11-15     4   90
352 2025-11-19     3   57
354 2025-11-21     3   72
355 2025-11-22     1   67

[94 rows x 3 columns]

### Пример 6: Фильтрация с объяснением шагов

In [ ]:
# Шаг 1: Создайте условие
# Шаг 2: Посмотрите на результат (Series из True/False)
# Шаг 3: Примените фильтр к DataFrame

---
## 4. Сложные условия

### Логические операторы:
- `&` - И (AND) - оба условия должны быть True
- `|` - ИЛИ (OR) - хотя бы одно условие True
- `~` - НЕ (NOT) - инверсия условия

### ВАЖНО:
Каждое условие должно быть в скобках!
```python
# Правильно:
df[(df['Temperature'] > 20) & (df['Humidity'] < 70)]

# Неправильно:
df[df['Temperature'] > 20 & df['Humidity'] < 70]
```

### Пример 7: Условие И (AND)

In [ ]:
# Найдите дни с температурой выше 20°C И влажностью ниже 70%
df[~((df['temp'] > 0) | (df['hum'] > 70))]

          date  temp  hum
1   2024-12-03    -3   57
4   2024-12-06    -8   50
7   2024-12-09    -9   69
9   2024-12-11    -6   69
10  2024-12-12    -4   57
..         ...   ...  ...
351 2025-11-18    -9   61
353 2025-11-20    -8   66
358 2025-11-25    -7   63
360 2025-11-27    -5   53
363 2025-11-30    -3   58

[118 rows x 3 columns]

### Пример 8: Условие ИЛИ (OR)

In [ ]:
# Найдите дни с очень низкой (< 15°C) ИЛИ очень высокой (> 30°C) температурой
df[(df['temp'] < -7) | (df['temp'] > 2)]

          date  temp  hum
0   2024-12-02   -10   96
4   2024-12-06    -8   50
5   2024-12-07     4   77
7   2024-12-09    -9   69
8   2024-12-10     3   83
..         ...   ...  ...
352 2025-11-19     3   57
353 2025-11-20    -8   66
354 2025-11-21     3   72
359 2025-11-26    -9   85
361 2025-11-28    -9   97

[142 rows x 3 columns]

### Пример 9: Условие НЕ (NOT)

In [ ]:
# Найдите дни без осадков (осадки == 0)
# Затем найдите дни С осадками, используя NOT
df[~(df.temp == 0)]

          date  temp  hum
0   2024-12-02   -10   96
1   2024-12-03    -3   57
2   2024-12-04    -2   89
3   2024-12-05    -5   99
4   2024-12-06    -8   50
..         ...   ...  ...
361 2025-11-28    -9   97
362 2025-11-29    -7   92
363 2025-11-30    -3   58
364 2025-12-01    -5   71
365 2025-12-02    -4   89

[346 rows x 3 columns]

### Пример 10: Проверка на вхождение в список (.isin())

In [ ]:
# Найдите дни с определенным описанием погоды
# Например: только 'Ясно' или 'Облачно'
df[df.temp.isin([-10,4,0])]

          date  temp  hum
0   2024-12-02   -10   96
5   2024-12-07     4   77
12  2024-12-14     4   60
13  2024-12-15   -10   95
14  2024-12-16   -10   82
..         ...   ...  ...
332 2025-10-30     0   65
334 2025-11-01     0   77
338 2025-11-05     4   60
344 2025-11-11   -10   53
348 2025-11-15     4   90

[74 rows x 3 columns]

---
## 5. Сортировка данных

### Метод .sort_values()
Сортирует DataFrame по значениям в колонке(ах).

**Параметры:**
- `by`: имя колонки или список колонок
- `ascending`: True (по возрастанию) или False (по убыванию)
- `inplace`: False (вернуть новый DF) или True (изменить исходный)

### Метод .sort_index()
Сортирует DataFrame по индексу.

### Пример 11: Сортировка по одной колонке

In [ ]:
# Отсортируйте данные по температуре (от холодной к теплой)

### Пример 12: Сортировка по убыванию

In [ ]:
# Отсортируйте по температуре от самой теплой к самой холодной

### Пример 13: Сортировка по нескольким колонкам

In [ ]:
# Отсортируйте сначала по описанию, затем по температуре

---
## 6. Метод .query()

**Альтернативный способ фильтрации** с более читаемым синтаксисом.

```python
# Вместо:
df[(df['Temperature'] > 25) & (df['Humidity'] < 70)]

# Можно:
df.query('Temperature > 25 and Humidity < 70')
```

Удобно для сложных запросов!

### Пример 14: Использование .query()

In [ ]:
# Используйте .query() для поиска комфортных дней:
# Температура 20-25°C, влажность < 70%, без осадков

---
## 7. Практические задачи

Примените изученные методы.

### Задача 1: Базовая фильтрация

**Задание**: Используя датасет о погоде:
1. Найдите все дни с температурой ниже 20°C
2. Найдите дни с влажностью выше 80%
3. Найдите дни с осадками больше 5 мм
4. Посчитайте, сколько таких дней в каждом случае (.shape[0] или len())

In [ ]:
# Ваш код здесь

### Задача 2: Сложные условия

**Задание**:
1. Найдите дни с температурой от 22 до 28°C (включительно)
2. Найдите дождливые дни (описание = 'Дождь') с температурой выше 20°C
3. Найдите дни, которые НЕ были ясными (описание != 'Ясно')
4. Найдите дни с высокой влажностью (>75%) ИЛИ осадками (>0)

**Подсказка**: используйте &, |, ~ и скобки

In [ ]:
# Ваш код здесь

### Задача 3: Использование loc и iloc

**Задание**:
1. Выберите строки с 10 по 20 используя iloc
2. Выберите первые 5 строк и только колонки 'Date', 'Temperature', 'Description'
3. Выберите последние 10 строк датасета
4. Выберите каждую 5-ую строку (используйте срез с шагом)

**Подсказка**: срезы работают так же как в списках Python

In [ ]:
# Ваш код здесь

### Задача 4: Топ-N значений

**Задание**:
1. Найдите топ-10 самых жарких дней (отсортируйте и возьмите первые 10)
2. Найдите топ-5 дней с наибольшими осадками
3. Найдите 10 дней с самой низкой влажностью
4. Для каждого случая выведите дату, температуру и соответствующий показатель

**Подсказка**: используйте .sort_values() и .head()

In [ ]:
# Ваш код здесь

### Задача 5: Комбинированный анализ

**Задание**: Проанализируйте "идеальные дни" для прогулки:
- Температура: 20-26°C
- Влажность: меньше 65%
- Ветер: меньше 15 км/ч
- Осадки: 0 мм

1. Отфильтруйте данные по всем этим условиям
2. Посчитайте, сколько таких дней
3. Выведите эти дни, отсортированные по температуре
4. Найдите среднюю температуру в эти "идеальные" дни

In [ ]:
# Ваш код здесь

### Задача 6: Работа с .isin() и .query()

**Задание**:
1. Используя .isin(), найдите дни с описанием 'Ясно' или 'Облачно'
2. Используя .query(), найдите дни с температурой 23-27°C и ветром < 20 км/ч
3. Сравните, какой способ вам удобнее

**Подсказка**: в .query() используйте `and` вместо `&`

In [ ]:
# Ваш код здесь

---
## 8. Дополнительные задачи (*)

Для тех, кто справился быстрее:

### Задача 7*: Анализ по сезонам

**Задание**: Если у вас есть колонка с датами:
1. Извлеките месяц из даты (используйте .dt.month)
2. Создайте новую колонку 'Season':
   - Зима: 12, 1, 2
   - Весна: 3, 4, 5
   - Лето: 6, 7, 8
   - Осень: 9, 10, 11
3. Найдите самый жаркий день в каждом сезоне
4. Найдите среднюю температуру по сезонам

**Подсказка**: используйте функцию или словарь для маппинга месяцев на сезоны

In [ ]:
# Ваш код здесь

### Задача 8*: Поиск паттернов

**Задание**: Найдите "аномальные" дни:
1. Вычислите среднюю температуру и стандартное отклонение
2. Аномалия = температура отклоняется от средней более чем на 2 стандартных отклонения
3. Найдите все такие дни
4. Определите, это "аномально жаркие" или "аномально холодные" дни

**Подсказка**: используйте .mean() и .std(), затем булеву индексацию

In [ ]:
# Ваш код здесь

### Задача 9*: Цепочка операций

**Задание**: Напишите одну цепочку операций (method chaining), которая:
1. Фильтрует дни с температурой > 20°C
2. Выбирает только колонки Date, Temperature, Humidity
3. Сортирует по влажности по возрастанию
4. Берет первые 10 строк

Все это должно быть в одной строке с использованием точечной нотации!

**Подсказка**: используйте \ для переноса длинных строк

In [ ]:
# Ваш код здесь

# Трансформация и очистка данных

In [ ]:
# Импорт библиотек

In [ ]:
# Создадим тестовый датасет с пропусками

---
## 1. Работа с пропущенными данными (NaN)

### Что такое NaN?
**NaN** (Not a Number) — специальное значение для отсутствующих данных.

### Причины появления пропусков:
- Данные не были собраны
- Ошибка при вводе
- Датчик не работал
- Просто нет информации

### Методы для работы с NaN:
- `.isnull()` / `.isna()` — найти пропуски (True/False)
- `.notnull()` / `.notna()` — найти НЕ пропуски
- `.fillna()` — заполнить пропуски
- `.dropna()` — удалить строки/столбцы с пропусками

### Пример 1: Обнаружение пропусков

In [ ]:
# Найдите пропуски в DataFrame
# Посчитайте количество пропусков по каждой колонке

### Пример 2: Заполнение пропусков константой

In [ ]:
# Заполните пропуски в температуре средним значением
# Заполните пропуски в осадках нулями

### Пример 3: Заполнение методом forward fill / backward fill

In [ ]:
# ffill - заполнить значением сверху
# bfill - заполнить значением снизу

### Пример 4: Удаление строк с пропусками

In [ ]:
# Удалите строки, где есть хотя бы один пропуск
# Удалите строки, где пропуски в конкретных колонках

---
## 2. Создание новых колонок

### Способы создания колонок:
1. Прямое присваивание: `df['new_col'] = value`
2. На основе вычислений: `df['new_col'] = df['col1'] + df['col2']`
3. На основе условий: `np.where()` или `df.loc[]`

### Пример 5: Простая колонка

In [ ]:
# Создайте колонку с температурой в Fahrenheit

### Пример 6: Колонка на основе условия

In [ ]:
# Создайте колонку 'Hot_Day' (True если temp > 25)
# Создайте колонку 'Weather_Category' (холодно/тепло/жарко)

### Пример 7: Использование np.where() и np.select()

In [ ]:
# np.where() для простого условия
# np.select() для множественных условий

---
## 3. Применение функций

### Методы для применения функций:
- `.apply()` — применить функцию к колонке или строке
- `.map()` — применить функцию/словарь к Series
- `.applymap()` — применить функцию к каждому элементу (устарело, используйте .map())

### Когда что использовать?
- **Векторизованные операции** (быстрее всего): `df['col'] * 2`
- **.apply()**: когда нужна сложная логика
- **.map()**: для замены значений или простых функций

### Пример 8: Применение встроенных функций

In [ ]:
# Примените .apply() с lambda функцией

### Пример 9: Применение пользовательской функции

In [ ]:
# Создайте функцию для категоризации температуры
# Примените её с помощью .apply()

### Пример 10: Использование .map() для замены значений

In [ ]:
# Используйте словарь для замены текстовых значений
# Например: 'Ясно' -> 'Sunny', 'Дождь' -> 'Rainy'

---
## 4. Изменение типов данных

### Основные типы данных:
- `int64` — целые числа
- `float64` — числа с плавающей точкой
- `object` — строки (текст)
- `bool` — булевы значения
- `datetime64` — даты и время
- `category` — категориальные данные (экономит память)

### Методы конвертации:
- `.astype()` — конвертация типа
- `pd.to_numeric()` — конвертация в число
- `pd.to_datetime()` — конвертация в дату

### Пример 11: Проверка и изменение типов

In [ ]:
# Проверьте типы данных (.dtypes)
# Конвертируйте температуру в int
# Конвертируйте описание в category

---
## 5. Работа с датами и временем

### Pandas datetime accessor (.dt)
После конвертации колонки в datetime, доступны специальные методы:
- `.dt.year` — год
- `.dt.month` — месяц
- `.dt.day` — день
- `.dt.dayofweek` — день недели (0=Пн)
- `.dt.day_name()` — название дня недели
- `.dt.month_name()` — название месяца
- `.dt.quarter` — квартал

### Пример 12: Парсинг дат

In [ ]:
# Создайте колонку с датами (строки)
# Конвертируйте в datetime с помощью pd.to_datetime()

### Пример 13: Извлечение компонентов даты

In [ ]:
# Создайте колонки: год, месяц, день, день недели

### Пример 14: Фильтрация по дате

In [ ]:
# Найдите данные за конкретный месяц
# Найдите данные за выходные дни

---
## 6. Практические задачи

### Задача 1: Очистка данных

**Задание**: Загрузите датасет с пропусками:
1. Найдите процент пропусков в каждой колонке
2. Заполните пропуски в температуре медианой
3. Заполните пропуски в осадках нулями
4. Удалите строки, где пропущено описание погоды
5. Проверьте, что пропусков больше нет

In [ ]:
# Ваш код здесь

### Задача 2: Создание признаков (Feature Engineering)

**Задание**: Создайте новые полезные колонки:
1. 'Temp_Range' — категория температуры:
   - 'Cold': < 15°C
   - 'Cool': 15-20°C
   - 'Warm': 20-25°C
   - 'Hot': > 25°C
2. 'Is_Rainy' — True если есть осадки
3. 'Comfort_Index' — температура * (100 - влажность) / 100
4. 'Season' — на основе месяца

In [ ]:
# Ваш код здесь

### Задача 3: Применение функций

**Задание**:
1. Напишите функцию, которая возвращает "Good" если температура 20-26°C и нет осадков, иначе "Bad"
2. Примените её к DataFrame с .apply()
3. Посчитайте, сколько "Good" и "Bad" дней

In [ ]:
# Ваш код здесь

### Задача 4: Работа с датами

**Задание**: Если у вас есть колонка с датами:
1. Извлеките день недели
2. Создайте колонку 'Is_Weekend' (True для Сб и Вс)
3. Найдите среднюю температуру по дням недели
4. Найдите самый жаркий день в каждом месяце

In [ ]:
# Ваш код здесь

### Задача 5: Комплексная трансформация

**Задание**: Создайте Pipeline обработки данных:
1. Загрузите сырые данные
2. Обработайте пропуски
3. Создайте новые признаки
4. Конвертируйте типы данных
5. Сохраните очищенные данные в новый CSV файл

In [ ]:
# Ваш код здесь

# Группировка и агрегация данных

---
## 1. Группировка данных (.groupby())

### Концепция Split-Apply-Combine

**GroupBy** работает в 3 этапа:
1. **Split** — разделить данные на группы
2. **Apply** — применить функцию к каждой группе
3. **Combine** — объединить результаты

### Синтаксис:
```python
df.groupby('column').agg_function()
```

### Зачем нужна группировка?
- Найти среднее по категориям
- Посчитать количество записей в группах
- Сравнить группы между собой

### Пример 1: Простая группировка

In [ ]:
# Сгруппируйте по месяцу и найдите среднюю температуру

### Пример 2: Группировка с разными агрегатными функциями

In [ ]:
# Используйте: .mean(), .sum(), .count(), .min(), .max(), .std()

---
## 2. Множественные агрегации

### Метод .agg()
Позволяет применить несколько функций одновременно.

### Пример 3: Множественные функции для одной колонки

In [ ]:
# Примените ['mean', 'min', 'max', 'std'] к температуре по месяцам

### Пример 4: Разные функции для разных колонок

In [ ]:
# Для температуры - среднее, для осадков - сумма

---
## 3. Группировка по нескольким колонкам

### Пример 5: Группировка по двум признакам

In [ ]:
# Сгруппируйте по месяцу и описанию погоды

---
## 4. Сводные таблицы (Pivot Tables)

### Что такое Pivot Table?
**Сводная таблица** — это способ реорганизации данных для лучшего анализа.

### Параметры .pivot_table():
- `values` — какие значения агрегировать
- `index` — строки таблицы
- `columns` — столбцы таблицы
- `aggfunc` — функция агрегации (по умолчанию mean)

### Пример 6: Простая pivot table

In [ ]:
# Создайте сводную таблицу: месяцы × описание погоды, значения - температура

### Пример 7: Pivot table с несколькими агрегациями

In [ ]:
# Используйте aggfunc=['mean', 'count']

---
## 5. Объединение данных

### Типы объединения:

1. **concat()** — склеивание DataFrame'ов вдоль оси
2. **merge()** — SQL-style join по ключевым колонкам
3. **join()** — объединение по индексу

### Типы merge (как в SQL):
- `inner` — только совпадающие записи
- `left` — все из левого + совпадающие из правого
- `right` — все из правого + совпадающие из левого
- `outer` — все записи из обоих

### Пример 8: Конкатенация DataFrames

In [ ]:
# Создайте два DataFrame и объедините их с помощью pd.concat()

### Пример 9: Merge (inner join)

In [ ]:
# Создайте два DataFrame с общей колонкой и объедините их
# Например: датасет погоды + датасет событий по датам

### Пример 10: Разные типы join

In [ ]:
# Сравните результаты inner, left, right, outer join

---
## 6. Практические задачи

### Задача 1: Анализ по месяцам

**Задание**: Используя датасет о погоде:
1. Сгруппируйте данные по месяцам
2. Для каждого месяца вычислите:
   - Среднюю температуру
   - Минимальную и максимальную температуру
   - Общее количество осадков
   - Количество дней
3. Найдите самый жаркий и самый холодный месяц

In [ ]:
# Ваш код здесь

### Задача 2: Анализ по типам погоды

**Задание**:
1. Сгруппируйте по описанию погоды ('Ясно', 'Облачно', 'Дождь')
2. Для каждого типа найдите:
   - Сколько таких дней было
   - Среднюю температуру
   - Среднюю влажность
3. Определите, какой тип погоды самый частый

In [ ]:
# Ваш код здесь

### Задача 3: Сводная таблица температур

**Задание**: Создайте сводную таблицу:
- Строки: месяцы
- Столбцы: тип погоды
- Значения: средняя температура

Визуально проанализируйте результат.

In [ ]:
# Ваш код здесь

### Задача 4: Объединение датасетов

**Задание**:
1. Создайте второй DataFrame с данными о транспорте (дата, количество поездок)
2. Объедините его с датасетом о погоде по дате
3. Проанализируйте: есть ли связь между погодой и количеством поездок?
4. Найдите среднее количество поездок при разных типах погоды

In [ ]:
# Ваш код здесь

### Задача 5: Группировка по нескольким признакам

**Задание**: Создайте мульти-индексную группировку:
1. Добавьте колонку 'Season' (сезон)
2. Сгруппируйте по сезону И типу погоды
3. Вычислите статистику по температуре для каждой комбинации
4. Найдите, в каком сезоне и при какой погоде самая высокая температура

In [ ]:
# Ваш код здесь

### Задача 6: Пользовательская агрегация

**Задание**:
1. Напишите функцию, которая вычисляет размах (range) = max - min
2. Сгруппируйте данные по месяцам
3. Примените вашу функцию к температуре
4. Найдите месяц с наибольшими колебаниями температуры

In [ ]:
# Ваш код здесь

---
## 7. Дополнительные задачи (*)

### Задача 7*: Скользящее среднее

**Задание**:
1. Вычислите 7-дневное скользящее среднее температуры (.rolling())
2. Сравните исходные значения с сглаженными
3. Найдите периоды устойчивого роста/снижения температуры

In [ ]:
# Ваш код здесь

### Задача 8*: Корреляционный анализ

**Задание**:
1. Вычислите корреляцию между всеми числовыми колонками (.corr())
2. Найдите пары признаков с сильной корреляцией
3. Интерпретируйте результаты

In [ ]:
# Ваш код здесь